# Generated by Django 6.0.3 on 2026-03-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ценовая категория',
                'verbose_name_plural': 'Ценовые категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.pricecategory', verbose_name='Ценовая категория')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoomElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=500, verbose_name='Название элемента')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный элемент')),
                ('min_price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.pricecategory', verbose_name='Ценовая категория')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IncompatibleRoomElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_element1', to='rooms.roomelement', verbose_name='Элемент 1')),
                ('incompatible_element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_element2', to='rooms.roomelement', verbose_name='Элемент 2')),
            ],
            options={
                'verbose_name': 'Несовместимые элементы',
                'verbose_name_plural': 'Несовместимые элементы',
                'ordering': ['id'],
            },
        ),
    ]
