# Generated by Django 6.0.3 on 2026-05-12 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementSort',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Название')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный элемент')),
            ],
            options={
                'verbose_name': 'Вид элемента',
                'verbose_name_plural': 'Виды элементов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoomElement',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Название элемента')),
                ('element_sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.elementsort', verbose_name='Вид элемента')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.hotelroomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Элемент номера',
                'verbose_name_plural': 'Элементы номеров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncompatibleRoomElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_element1', to='rooms.hotelroomelement', verbose_name='Элемент 1')),
                ('incompatible_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_element2', to='rooms.hotelroomelement', verbose_name='Элемент 2')),
            ],
            options={
                'verbose_name': 'Несовместимые элементы номеров',
                'verbose_name_plural': 'Несовместимые элементы номеров',
                'constraints': [models.UniqueConstraint(fields=('element', 'incompatible_element'), name='unique_incompatibility'), models.CheckConstraint(condition=models.Q(('element', models.F('incompatible_element')), _negated=True), name='prevent_self_incompatibility')],
            },
        ),
    ]
