# Generated by Django 6.0.3 on 2026-05-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный элемент')),
            ],
            options={
                'verbose_name': 'Тип элемента',
                'verbose_name_plural': 'Типы элементов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип комнаты',
                'verbose_name_plural': 'Типы комнат',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoomElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название элемента')),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.elementtype', verbose_name='Тип элемента')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='Подходящий тип комнаты')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='Тип комнаты')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IncompatibleRoomElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_element1', to='rooms.roomelement', verbose_name='Элемент 1')),
                ('incompatible_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_element2', to='rooms.roomelement', verbose_name='Элемент 2')),
            ],
            options={
                'verbose_name': 'Несовместимые элементы',
                'verbose_name_plural': 'Несовместимые элементы',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('element', 'incompatible_element'), name='unique_incompatibility')],
            },
        ),
        migrations.CreateModel(
            name='RoomElementAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomelement', verbose_name='Элемент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Связь комната-элемент',
                'verbose_name_plural': 'Связи комната-элемент',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('room', 'element'), name='unique_room_element_assignment')],
            },
        ),
    ]
