# Generated by Django 6.0.3 on 2026-05-12 10:35

from django.db import migrations

def seed_element_sort(apps, schema_editor):
    ElementSort = apps.get_model('rooms', 'ElementSort')
    sorts = [
        ("Кровать", True),
        ("Стол", True),
        ("Стул", True),
        ("Унитаз", True),
        ("Раковина", True),
        ("Мультиварка", False),
        ("Кофеварка", False),
        ("Тостер", False),
        ("Увлажнитель воздуха", False),
        ("Отпариватель", False),
        ("Радиоприемник", False),
        ("Телевизор", False),
        ("Холодильник", False),
    ]
    for name, is_required in sorts:
        ElementSort.objects.create(name=name, is_required=is_required)

class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_element_sort),
    ]
