# Generated by Django 6.0.3 on 2026-05-12 10:41

from django.db import migrations

def seed_hotel_room_type(apps, schema_editor):
    hotel_room_type = apps.get_model('rooms', 'HotelRoomType')
    types = [
        "Стандарт",
        "Эконом",
        "Люкс",
    ]
    for name in types:
        hotel_room_type.objects.create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_seed_element_sort'),
    ]

    operations = [
        migrations.RunPython(seed_hotel_room_type),
    ]
