# Generated by Django 6.0.3 on 2026-05-12 10:48

from django.db import migrations

def seed_hotel_room_element(apps, schema_editor):
    hotel_room_element = apps.get_model('rooms', 'HotelRoomElement')
    hotel_room_type = apps.get_model('rooms', 'HotelRoomType')
    element_sort = apps.get_model('rooms', 'ElementSort')

    standard = hotel_room_type.objects.get(name="Стандарт")
    economy = hotel_room_type.objects.get(name="Эконом")
    luxury = hotel_room_type.objects.get(name="Люкс")

    bed = element_sort.objects.get(name="Кровать")
    table = element_sort.objects.get(name="Стол")
    chair = element_sort.objects.get(name="Стул")
    toilet = element_sort.objects.get(name="Унитаз")
    sink = element_sort.objects.get(name="Раковина")
    microwave = element_sort.objects.get(name="Мультиварка")
    coffee_maker = element_sort.objects.get(name="Кофеварка")
    toaster = element_sort.objects.get(name="Тостер")
    humidifier = element_sort.objects.get(name="Увлажнитель воздуха")
    steamer = element_sort.objects.get(name="Отпариватель")
    radio = element_sort.objects.get(name="Радиоприемник")
    tv = element_sort.objects.get(name="Телевизор")
    fridge = element_sort.objects.get(name="Холодильник")

    elements = [
        # Economy - Кровати
        ("Кровать МОРИ", economy, bed),
        ("Кровать ЛОРА", economy, bed),
        ("Кровать БЕРГ М", economy, bed),
        # Economy - Столы
        ("Стол Орех", economy, table),
        ("Стол Коффик", economy, table),
        ("Стол Кангас", economy, table),
        # Economy - Стулья
        ("Стул Gigant", economy, chair),
        ("Стул Каст", economy, chair),
        ("Стул Адосс", economy, chair),
        # Economy - Унитазы
        ("Унитаз Компакт", economy, toilet),
        ("Унитаз Эконом", economy, toilet),
        ("Унитаз Стандарт", economy, toilet),
        # Economy - Раковины
        ("Раковина Овал", economy, sink),
        ("Раковина Прямоугольная", economy, sink),
        ("Раковина Компактная", economy, sink),
        # Economy - Мультиварки
        ("Мультиварка Scarlett", economy, microwave),
        ("Мультиварка Vitek", economy, microwave),
        ("Мультиварка Galaxy", economy, microwave),
        # Economy - Кофеварки
        ("Кофеварка Maxwell", economy, coffee_maker),
        ("Кофеварка Polaris", economy, coffee_maker),
        ("Кофеварка Lumme", economy, coffee_maker),
        # Economy - Тостеры
        ("Тостер Philips", economy, toaster),
        ("Тостер Bosch", economy, toaster),
        ("Тостер Russell Hobbs", economy, toaster),
        # Economy - Увлажнители
        ("Увлажнитель Ballu", economy, humidifier),
        ("Увлажнитель Boneco", economy, humidifier),
        ("Увлажнитель AirComfort", economy, humidifier),
        # Economy - Отпариватели
        ("Отпариватель Vapo", economy, steamer),
        ("Отпариватель Astoria", economy, steamer),
        ("Отпариватель Sinbo", economy, steamer),
        # Economy - Радиоприемники
        ("Радиоприемник Philips", economy, radio),
        ("Радиоприемник Sony", economy, radio),
        ("Радиоприемник Panasonic", economy, radio),
        # Economy - Телевизоры
        ("Телевизор LG 32", economy, tv),
        ("Телевизор Samsung 32", economy, tv),
        ("Телевизор Yasin 32", economy, tv),
        # Economy - Холодильники
        ("Холодильник Indesit", economy, fridge),
        ("Холодильник Artel", economy, fridge),
        ("Холодильник Midea", economy, fridge),

        # Standard - Кровати
        ("Кровать МОРИ ЛЮКС", standard, bed),
        ("Кровать ЛОРА ПЛЮС", standard, bed),
        ("Кровать БЕРГ L", standard, bed),
        # Standard - Столы
        ("Стол Дуб", standard, table),
        ("Стол Венге", standard, table),
        ("Стол Ясень", standard, table),
        # Standard - Стулья
        ("Стул Gigant Pro", standard, chair),
        ("Стул Каст Plus", standard, chair),
        ("Стул Адосс Lux", standard, chair),
        # Standard - Унитазы
        ("Унитаз Комфорт", standard, toilet),
        ("Унитаз Стандарт Plus", standard, toilet),
        ("Унитаз Премиум", standard, toilet),
        # Standard - Раковины
        ("Раковина Овал Керамика", standard, sink),
        ("Раковина Прямоугольная Керамика", standard, sink),
        ("Раковина Фарфоровая", standard, sink),
        # Standard - Мультиварки
        ("Мультиварка Scarlett Pro", standard, microwave),
        ("Мультиварка Vitek Premium", standard, microwave),
        ("Мультиварка Galaxy Lux", standard, microwave),
        # Standard - Кофеварки
        ("Кофеварка Maxwell Premium", standard, coffee_maker),
        ("Кофеварка Polaris Pro", standard, coffee_maker),
        ("Кофеварка Lumme Plus", standard, coffee_maker),
        # Standard - Тостеры
        ("Тостер Philips Premium", standard, toaster),
        ("Тостер Bosch Plus", standard, toaster),
        ("Тостер Russell Hobbs Pro", standard, toaster),
        # Standard - Увлажнители
        ("Увлажнитель Ballu Pro", standard, humidifier),
        ("Увлажнитель Boneco Plus", standard, humidifier),
        ("Увлажнитель AirComfort Premium", standard, humidifier),
        # Standard - Отпариватели
        ("Отпариватель Vapo Pro", standard, steamer),
        ("Отпариватель Astoria Plus", standard, steamer),
        ("Отпариватель Sinbo Lux", standard, steamer),
        # Standard - Радиоприемники
        ("Радиоприемник Philips Premium", standard, radio),
        ("Радиоприемник Sony Pro", standard, radio),
        ("Радиоприемник Panasonic Plus", standard, radio),
        # Standard - Телевизоры
        ("Телевизор LG 43", standard, tv),
        ("Телевизор Samsung 43", standard, tv),
        ("Телевизор Yasin 43", standard, tv),
        # Standard - Холодильники
        ("Холодильник Indesit Plus", standard, fridge),
        ("Холодильник Artel Premium", standard, fridge),
        ("Холодильник Midea Pro", standard, fridge),

        # Luxury - Кровати
        ("Кровать МОРИ ЛЮКС VIP", luxury, bed),
        ("Кровать ЛОРА ROYAL", luxury, bed),
        ("Кровать БЕРГ XL", luxury, bed),
        # Luxury - Столы
        ("Стол Красное дерево", luxury, table),
        ("Стол Орех черный", luxury, table),
        ("Стол Ясень премиум", luxury, table),
        # Luxury - Стулья
        ("Стул Gigant Royal", luxury, chair),
        ("Стул Каст Platinum", luxury, chair),
        ("Стул Адосс Royal", luxury, chair),
        # Luxury - Унитазы
        ("Унитаз Люкс", luxury, toilet),
        ("Унитаз Премиум Plus", luxury, toilet),
        ("Унитаз Royal", luxury, toilet),
        # Luxury - Раковины
        ("Раковина Мраморная", luxury, sink),
        ("Раковина Гранит", luxury, sink),
        ("Раковина Оникс", luxury, sink),
        # Luxury - Мультиварки
        ("Мультиварка Moulinex Premium", luxury, microwave),
        ("Мультиварка Redmond Lux", luxury, microwave),
        ("Мультиварка Polaris Royal", luxury, microwave),
        # Luxury - Кофеварки
        ("Кофеварка Delonghi Magnifica", luxury, coffee_maker),
        ("Кофеварка Jura E6", luxury, coffee_maker),
        ("Кофеварка Siemens TI", luxury, coffee_maker),
        # Luxury - Тостеры
        ("Тостер Dualit Classic", luxury, toaster),
        ("Тостер Magimix Vision", luxury, toaster),
        ("Тостер Sage by Heston Blumenthal", luxury, toaster),
        # Luxury - Увлажнители
        ("Увлажнитель Dyson Humidify", luxury, humidifier),
        ("Увлажнитель Stadler Form Oskar", luxury, humidifier),
        ("Увлажнитель Venta LW62", luxury, humidifier),
        # Luxury - Отпариватели
        ("Отпариватель Tefal Pro Express", luxury, steamer),
        ("Отпариватель Rowenta Master", luxury, steamer),
        ("Отпариватель Polti Vaporella", luxury, steamer),
        # Luxury - Радиоприемники
        ("Радиоприемник Bang & Olufsen", luxury, radio),
        ("Радиоприемник Bose Wave", luxury, radio),
        ("Радиоприемник Nubert", luxury, radio),
        # Luxury - Телевизоры
        ("Телевизор LG OLED 55", luxury, tv),
        ("Телевизор Samsung QLED 55", luxury, tv),
        ("Телевизор Sony Bravia 55", luxury, tv),
        # Luxury - Холодильники
        ("Холодильник Sub-Zero Pro", luxury, fridge),
        ("Холодильник Gaggenau Premium", luxury, fridge),
        ("Холодильник Liebherr Luxe", luxury, fridge),
    ]

    for name, room_type, element_sort in elements:
        hotel_room_element.objects.create(
            name=name,
            room_type=room_type,
            element_sort=element_sort
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_seed_hotel_room_type'),
    ]

    operations = [
        migrations.RunPython(seed_hotel_room_element),
    ]
