# Generated by Django 6.0.3 on 2026-05-12 11:13

from django.db import migrations

def seed_incompatible_room_element(apps, schema_editor):
    incompatible_room_element = apps.get_model('rooms', 'IncompatibleRoomElement')
    hotel_room_element = apps.get_model('rooms', 'HotelRoomElement')
    
    # Несовместимости для Economy
    economy_incompatibilities = [
        ("Кровать МОРИ", "Холодильник Indesit"),
        ("Стол Орех", "Мультиварка Scarlett"),
        ("Стул Gigant", "Тостер Philips"),
        ("Унитаз Компакт", "Раковина Овал"),
        ("Телевизор LG 32", "Радиоприемник Philips"),
    ]
    
    # Несовместимости для Standard
    standard_incompatibilities = [
        ("Кровать МОРИ ЛЮКС", "Холодильник Indesit Plus"),
        ("Стол Дуб", "Мультиварка Vitek Premium"),
        ("Стул Gigant Pro", "Тостер Bosch Plus"),
        ("Унитаз Комфорт", "Раковина Овал Керамика"),
        ("Телевизор LG 43", "Радиоприемник Philips Premium"),
    ]
    
    # Несовместимости для Luxury
    luxury_incompatibilities = [
        ("Кровать МОРИ ЛЮКС VIP", "Холодильник Sub-Zero Pro"),
        ("Стол Красное дерево", "Мультиварка Moulinex Premium"),
        ("Стул Gigant Royal", "Тостер Dualit Classic"),
        ("Унитаз Люкс", "Раковина Мраморная"),
        ("Телевизор LG OLED 55", "Радиоприемник Bang & Olufsen"),
    ]
    
    all_incompatibilities = economy_incompatibilities + standard_incompatibilities + luxury_incompatibilities
    
    for element1_name, element2_name in all_incompatibilities:
        element1 = hotel_room_element.objects.get(name=element1_name)
        element2 = hotel_room_element.objects.get(name=element2_name)
        
        incompatible_room_element.objects.create(
            element=element1,
            incompatible_element=element2
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_seed_hotel_room_element'),
    ]

    operations = [
        migrations.RunPython(seed_incompatible_room_element),
    ]
