# Generated by Django 6.0.3 on 2026-05-15 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_seed_incompatible_room_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalElementSort',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид дополнительного элемента',
                'verbose_name_plural': 'Виды дополнительных элементов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalHotelRoomElement',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Название элемента')),
                ('cost', models.FloatField(verbose_name='Цена элемента')),
            ],
            options={
                'verbose_name': 'Дополнительный элемент номера',
                'verbose_name_plural': 'Дополнительные элементы номера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncompatibleHotelRoomElement_AdditionalToAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Несовместимые дополнительные элементы номера',
                'verbose_name_plural': 'Несовместимые дополнительные элементы номера',
            },
        ),
        migrations.CreateModel(
            name='IncompatibleHotelRoomElement_RequiredToAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Несовместимые обязательные и дополнительные элементы номера',
                'verbose_name_plural': 'Несовместимые обязательные и дополнительные элементы номера',
            },
        ),
        migrations.CreateModel(
            name='IncompatibleHotelRoomElement_RequiredToRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Несовместимые обязательные элементы номера',
                'verbose_name_plural': 'Несовместимые обязательные элементы номера',
            },
        ),
        migrations.CreateModel(
            name='RequiredElementSort',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид обязательного элемента',
                'verbose_name_plural': 'Виды обязательных элементов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequiredHotelRoomElement',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Название элемента')),
                ('cost', models.FloatField(verbose_name='Цена элемента')),
            ],
            options={
                'verbose_name': 'Обязательный элемент номера',
                'verbose_name_plural': 'Обязательные элементы номера',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='hotelroomelement',
            name='element_sort',
        ),
        migrations.RemoveField(
            model_name='hotelroomelement',
            name='room_type',
        ),
        migrations.RemoveConstraint(
            model_name='incompatibleroomelement',
            name='unique_incompatibility',
        ),
        migrations.RemoveConstraint(
            model_name='incompatibleroomelement',
            name='prevent_self_incompatibility',
        ),
        migrations.AddField(
            model_name='additionalhotelroomelement',
            name='element_sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.additionalelementsort', verbose_name='Вид элемента'),
        ),
        migrations.AddField(
            model_name='additionalhotelroomelement',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.hotelroomtype', verbose_name='Тип номера'),
        ),
        migrations.AddField(
            model_name='incompatiblehotelroomelement_additionaltoadditional',
            name='element1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_additional_as_element1', to='rooms.additionalhotelroomelement', verbose_name='Элемент 1'),
        ),
        migrations.AddField(
            model_name='incompatiblehotelroomelement_additionaltoadditional',
            name='element2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_additional_as_element2', to='rooms.additionalhotelroomelement', verbose_name='Элемент 2'),
        ),
        migrations.AddField(
            model_name='incompatiblehotelroomelement_requiredtoadditional',
            name='element2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_required_to_additional_as_element2', to='rooms.additionalhotelroomelement', verbose_name='Элемент 2'),
        ),
        migrations.AddField(
            model_name='requiredhotelroomelement',
            name='element_sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.requiredelementsort', verbose_name='Вид элемента'),
        ),
        migrations.AddField(
            model_name='requiredhotelroomelement',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.hotelroomtype', verbose_name='Тип номера'),
        ),
        migrations.AddField(
            model_name='incompatiblehotelroomelement_requiredtorequired',
            name='element1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_required_as_element1', to='rooms.requiredhotelroomelement', verbose_name='Элемент 1'),
        ),
        migrations.AddField(
            model_name='incompatiblehotelroomelement_requiredtorequired',
            name='element2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_required_as_element2', to='rooms.requiredhotelroomelement', verbose_name='Элемент 2'),
        ),
        migrations.AddField(
            model_name='incompatiblehotelroomelement_requiredtoadditional',
            name='element1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_required_to_additional_as_element1', to='rooms.requiredhotelroomelement', verbose_name='Элемент 1'),
        ),
        migrations.DeleteModel(
            name='ElementSort',
        ),
        migrations.RemoveField(
            model_name='incompatibleroomelement',
            name='element',
        ),
        migrations.RemoveField(
            model_name='incompatibleroomelement',
            name='incompatible_element',
        ),
        migrations.AddConstraint(
            model_name='incompatiblehotelroomelement_additionaltoadditional',
            constraint=models.UniqueConstraint(fields=('element1', 'element2'), name='unique_incompatibility_additional_additional'),
        ),
        migrations.AddConstraint(
            model_name='incompatiblehotelroomelement_additionaltoadditional',
            constraint=models.CheckConstraint(condition=models.Q(('element1', models.F('element2')), _negated=True), name='prevent_self_incompatibility_additional_additional'),
        ),
        migrations.AddConstraint(
            model_name='incompatiblehotelroomelement_requiredtorequired',
            constraint=models.UniqueConstraint(fields=('element1', 'element2'), name='unique_incompatibility_required_required'),
        ),
        migrations.AddConstraint(
            model_name='incompatiblehotelroomelement_requiredtorequired',
            constraint=models.CheckConstraint(condition=models.Q(('element1', models.F('element2')), _negated=True), name='prevent_self_incompatibility_required_required'),
        ),
        migrations.AddConstraint(
            model_name='incompatiblehotelroomelement_requiredtoadditional',
            constraint=models.UniqueConstraint(fields=('element1', 'element2'), name='unique_incompatibility_required_additional'),
        ),
        migrations.AddConstraint(
            model_name='incompatiblehotelroomelement_requiredtoadditional',
            constraint=models.CheckConstraint(condition=models.Q(('element1', models.F('element2')), _negated=True), name='prevent_self_incompatibility_required_additional'),
        ),
        migrations.DeleteModel(
            name='HotelRoomElement',
        ),
        migrations.DeleteModel(
            name='IncompatibleRoomElement',
        ),
    ]
